apps/crud/models.py
from apps.app import db


# Userクラスの作成
class User(db.Model):
    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String)

apps/crud/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField


# ユーザー新規作成フォーム
class UserForm(FlaskForm):
    class Meta:
        csrf = False
    username = StringField(
        "ユーザー名",
    )
    submit = SubmitField("新規登録")

apps/crud/__init__.py
import apps.crud.models

apps/crud/views.py
from flask import Blueprint, render_template, redirect, url_for
from apps.crud.forms import UserForm
from apps.app import db
from apps.crud.models import User

crud = Blueprint(
    "crud",
    __name__,
    template_folder="templates",
)


# indexエンドポイント
@crud.route("/")
def index():
    return render_template("crud/index.html")


# 新規登録
@crud.route("/users/new", methods=["POST", "GET"])
def create_user():
    form = UserForm()

    if form.submit.data:
        user = User(
            username=form.username.data,
        )
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("crud.users"))
    return render_template("crud/create.html", form=form)


# ユーザー一覧
@crud.route("/users")
def users():
    users = User.query.all()
    return render_template("crud/index.html", users=users)


# 編集
@crud.route("/users/<user_id>", methods=["POST", "GET"])
def edit_user(user_id):
    form = UserForm()

    user = User.query.filter_by(id=user_id).first()

    if form.submit.data:
        user.username = form.username.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("crud.users"))

    return render_template("crud/edit.html", user=user, form=form)


# 削除用
@crud.route("/users/<user_id>/delete", methods=["POST"])
def delete_user(user_id):
    user = User.query.filter_by(id=user_id).first()
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for("crud.users"))

apps/crud/templates/crud/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ユーザー新規登録</title>
</head>
<body>
    <h2>ユーザー新規登録</h2>
    <form action="{{ url_for('crud.create_user') }}" method="post" novalidate="novalidate">
        <p>{{ form.username.label }} {{ form.username }}</p>
        <p>{{ form.submit }}</p>
    </form>
</body>
</html>

apps/crud/templates/crud/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ユーザー編集</title>
</head>
<body>
    <h2>ユーザー編集</h2>
    <form action="{{ url_for('crud.edit_user', user_id=user.id) }}" method="post">
        <p>{{ form.username.label }} {{ form.username(value=user.username) }}</p>
        <p>{{ form.submit(value="更新") }}</p>
    </form>
    <form action="{{ url_for('crud.delete_user', user_id=user.id) }}" method="post">
        <input type="submit" value="削除">
    </form>
</body>
</html>

apps/crud/templates/crud/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRUD</title>
</head>
<body>
    <h2>ユーザーの一覧</h2>
    <a href="{{ url_for('crud.create_user') }}">ユーザー新規登録</a>

    <table>
        <tr>
            <th>ID</th>
            <th>ユーザー名</th>
        </tr>
        {% for user in users %}
        <tr>
            <td><a href="{{ url_for('crud.edit_user', user_id=user.id) }}">{{ user.id }}</a></td>
            <td>{{ user.username }}</td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>